# -*- coding: utf-8 -*-
"""変数を使って四則演算しよう

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LnzU3niKvhmur22v6Z7MvaGxiaeL0q2B
"""

# 上辺：10cm
# 下辺：20cm
# 高さ：5cm
# 公式：台形の面積 =（上辺＋下辺）× 高さ ÷ 2
zyouhen = 10
teihen = 20
high = 5
menseki = (zyouhen + teihen) * high / 2
print(str(menseki), "cm2")